project:
  type: website
  output-dir: _site

website:
  title: "HEALTH4EARTH"
  navbar:
    left:
      - text: "Carte"
        href: index.qmd
      - text: "MÃ©thodologie"
        href: methods.qmd
      - text: "Documentation"
        href: docs.qmd

format:
  html:
    theme: cosmo
    toc: true
