project:
  type: website
<<<<<<< HEAD:website/_quarto.yml
  output-dir: docs
=======
>>>>>>> 5d5d0c1375793b70ba3ef2a801cdcd19cb90a4fa:quarto_site/_quarto.yml

website:
  title: "Health4Earth"
  navbar:
    left:
      - text: Accueil
<<<<<<< HEAD:website/_quarto.yml
        href: quarto_site/index.qmd
      - text: Données
        href: quarto_site/data.qmd
      - text: Analyse
        href: quarto_site/analysis.qmd
      - text: Modèle
        href: quarto_site/model.qmd
      - text: Équipe
        href: quarto_site/team.qmd
=======
        href: index.qmd
      - text: Données
        href: data.qmd
      - text: Visualisations
        href: visualisations.qmd
  page-footer:
    left: "Projet académique — Master Statistique & Science des Données"
    right: "© 2025 AGOSSOU Dossou Modeste 
                   KARIMOU Firdaousse
                   Ollier Julier"
>>>>>>> 5d5d0c1375793b70ba3ef2a801cdcd19cb90a4fa:quarto_site/_quarto.yml
