project:
  type: website
  output-dir: _site
  resources:
    - "api/**"

website:
  title: "Health4Earth"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: analysis.qmd
        text: Analyse Exploratoire
      - href: predictions.qmd
        text: Prédictions
      - href: methods.qmd
        text: Méthodologie
      - href: api/index.html
        text: Documentation

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    page-layout: article