project:
  type: website
  output-dir: _site
  resources:
    - "api/**"

website:
  title: "Health4Earth"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: analysis.qmd
        text: Analyse Exploratoire
      - href: predictions_france.qmd
        text: Pr√©diction France
      - href: documentation.qmd
        text: Documentation

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    page-layout: article
    mainfont: "Segoe UI"