project:
  type: website
  output-dir: _site

website:
  title: "Health4Earth"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: map.qmd
        text: Carte Interactive
      - href: api/index.html
        text: Documentation

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true