project:
  type: website
  output-dir: _site
  resources:
    - "api/**"

website:
  title: "Health4Earth"
  navbar:
    left:
      - href: index.qmd
        text: Accueil & Carte
      - href: dashboard.qmd
        text: Analyse & Prédictions
      - href: code.qmd
        text: Code Source
      - href: methods.qmd
        text: Méthodologie
      - href: api/index.html
        text: Documentation API

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true